### ISSUE TITLE
Is there a way to force slots to occur at the same time?

### ISSUE THREAD

**Issue by FunkyLoveCow** [PyconUK/ConferenceScheduler#106]
A bit of background on my problem:

I work for a school that has intervention periods for students with higher needs in certain subjects. Not all students in the school require this service, but many do. This is done by having a dedicated staff for these interventions that reach into the classrooms, pull out the handful of students that need smaller/one-on-one time for a subject, and then return the student to their regular class after the daily time is over. Then the staff moves on to the next block of students and does the same thing.

Each year it is a huge hassle to gather schedules for each grade level (what time are they teaching specific subjects because we don't want to pull a student out for reading help when they are going over science lessons), times for other courses (art, music, physical education, because we can't pull them out during that time), lunches and recess and associating that with how much time each student requires (Student A may require 20 minutes of reading help, Students B, C, D may need 30 minutes of ESL services).

---

With that background, I've been looking at this and watching the 2016 PyConUK talk and think this could get close to what I need. My trouble has been trying to figure out how to group certain students together. I see that `tags` in an Event are used for batch unavailability. Is there an opposite? I want to have certain groups of students together (ie. 3-4 with the same required time for the same subject). I don't need every student to be one-on-one.

**Comment by meatballs** [comment]
Interesting problem!

I can't think of a way to do this with the library at the moment. We have a built-in constraint that each slot can host a maximum of one event and it seems to me that you would need that relaxed. That way, you could model individual students as events that need to be scheduled and the teachers as slots.

I'll ponder it and see if something comes to mind...

**Comment by meatballs** [comment]
We've not been able to come up with a way to solve this using this library. I think you would have to formulate your own ILP problem to solve this one.
