### ISSUE TITLE
Issue with Slot times and datetime while running tutorial code

### ISSUE THREAD

**Issue by nicholasdiao** [PyconUK/ConferenceScheduler#107]
Hi, 

I am running the tutorial code, and I am getting an error when I get to the following lines. 

`schedule = scheduler.schedule(events, slots)`

The issue originates from line 104 in the utils.py file:

`startdate = datetime.datetime.strptime(slot.starts_at, '%d-%b-%Y %H:%M')`

And the error says: TypeError: strptime() argument 1 must be str, not datetime.datetime

Here is all the code I am running: 

`from datetime import datetime
from conference_scheduler.resources import Slot, Event
from conference_scheduler.resources import Slot, Event

talk_slots  = [Slot(venue='Big', starts_at=datetime(2016, 9, 15, 9, 30), duration=30, session="A", capacity=200),
                Slot(venue='Big', starts_at=datetime(2016, 9, 15, 10, 0), duration=30, session="A", capacity=200),
               Slot(venue='Small', starts_at=datetime(2016, 9, 15, 9, 30), duration=30, session="B", capacity=50),
                Slot(venue='Small', starts_at=datetime(2016, 9, 15, 10, 0), duration=30, session="B", capacity=50),
                Slot(venue='Big', starts_at=datetime(2016, 9, 15, 12, 30), duration=30, session="C", capacity=200),
                Slot(venue='Big', starts_at=datetime(2016, 9, 15, 13, 0), duration=30, session="C", capacity=200),
                Slot(venue='Small', starts_at=datetime(2016, 9, 15, 12, 30), duration=30, session="D", capacity=50),
                Slot(venue='Small', starts_at=datetime(2016, 9, 15, 13, 0), duration=30, session="D", capacity=50),
                Slot(venue='Big', starts_at=datetime(2016, 9, 16, 9, 30), duration=30, session="E", capacity=50),
                Slot(venue='Big', starts_at=datetime(2016, 9, 16, 10, 00), duration=30, session="E", capacity=50),
                Slot(venue='Big', starts_at=datetime(2016, 9, 16, 12, 30), duration=30, session="F", capacity=50),
                Slot(venue='Big', starts_at=datetime(2016, 9, 16, 13, 0), duration=30, session="F", capacity=50)]

workshop_slots = [Slot(venue='Small', starts_at=datetime(2016, 9, 16, 9, 30), duration=60, session="G", capacity=50),
                   Slot(venue='Small', starts_at=datetime(2016, 9, 16, 13, 0), duration=60, session="H", capacity=50)]
outside_slots = [Slot(venue='Outside', starts_at=datetime(2016, 9, 16, 12, 30), duration=90, session="I", capacity=1000),
                  Slot(venue='Outside', starts_at=datetime(2016, 9, 16, 13, 0), duration=90, session="J", capacity=1000)]
slots = talk_slots + workshop_slots + outside_slots

events = [Event(name='Talk 1', duration=30, tags=['beginner'], unavailability=outside_slots[:], demand=50),
          Event(name='Talk 2', duration=30, tags=['beginner'], unavailability=outside_slots[:], demand=130),
          Event(name='Talk 3', duration=30, tags=['beginner'], unavailability=outside_slots[:], demand=200),
          Event(name='Talk 4', duration=30, tags=['beginner'], unavailability=outside_slots[:], demand=30),
          Event(name='Talk 5', duration=30, tags=['intermediate'], unavailability=outside_slots[:], demand=60),
          Event(name='Talk 6', duration=30, tags=['intermediate'], unavailability=outside_slots[:], demand=30),
          Event(name='Talk 7', duration=30, tags=['intermediate', 'advanced'], unavailability=outside_slots[:], demand=60),
          Event(name='Talk 8', duration=30, tags=['intermediate', 'advanced'], unavailability=outside_slots[:], demand=60),
          Event(name='Talk 9', duration=30, tags=['advanced'], unavailability=outside_slots[:], demand=60),
          Event(name='Talk 10', duration=30, tags=['advanced'], unavailability=outside_slots[:], demand=30),
          Event(name='Talk 11', duration=30, tags=['advanced'], unavailability=outside_slots[:], demand=30),
          Event(name='Talk 12', duration=30, tags=['advanced'], unavailability=outside_slots[:], demand=30),
          Event(name='Workshop 1', duration=60, tags=['testing'], unavailability=outside_slots[:], demand=40),
          Event(name='Workshop 2', duration=60, tags=['testing'], unavailability=outside_slots[:], demand=40),
          Event(name='City tour', duration=90, tags=[], unavailability=talk_slots[:] + workshop_slots[:], demand=100),
          Event(name='Boardgames', duration=90, tags=[], unavailability=talk_slots[:] + workshop_slots[:], demand=20)]

events[0].add_unavailability(events[6])

events[13].add_unavailability(events[-1])

from conference_scheduler import scheduler
schedule = scheduler.schedule(events, slots)`

This is straight from the code on the tutorial: http://conference-scheduler.readthedocs.io/en/latest/tutorial/index.html#inputting-the-data

Can someone help me with this issue?

Thanks

**Comment by meatballs** [comment]
What version of the library are you using? The tutorial is based on the current release (3.0.1) and that error looks like something from older versions as does that line from utils.py
