### ISSUE TITLE
can we use this to schedule meetings?

### ISSUE THREAD

**Issue by tiru1930** [PyconUK/ConferenceScheduler#109]
Hi

Can this library useful to get non overlapping meeting timings if we give busy slots and free slots of the person? 
i.e i have group of people their event list from google calendar and their all slots. on give time period. can use this data to get all possible free slots

**Comment by drvinceknight** [comment]
It might be a bit tricky as in meetings the whole point is to ensure there is overlap (as opposed to the conference scheduler). If you're just aiming to find free slots, using python sets and looking at intersections might be what you need.
