### ISSUE TITLE
Have sessions in slots

### ISSUE THREAD

**Issue by drvinceknight** [PyconUK/ConferenceScheduler#17]
In a similar vain to unavailability etc... The problem is fundamentally one of events and slots. As sessions are collections of slots we could just include a session attribute in the slot class. This just means that the **only variables that get passed to the mathematical problem are events and slots** (which makes things clean).

(We could keep the sessions class as they are in case they're useful further down the line and ensure through preprocessing that the sessions instances are all correctly in the slot `sessions` attribute.)

**Comment by drvinceknight** [comment]
Although perhaps having this circular relationship would not be a good thing.

**Comment by meatballs** [comment]
Yeah, I'd thought that too. Just haven't done anything about it!

**Comment by meatballs** [comment]
The only reason for keeping the session class might be as a handy way of defining the incoming data.

**Comment by meatballs** [comment]
But I'm not wholly convinced even of that!

**Comment by drvinceknight** [comment]
I think the sessions should be in slots. It's essentially a tag on sessions anyway. 

From the ilp's pov this would also set the precedent that as new constraints, objectives etc come the corresponding data just needs to be added to the slots and events. We don't have to worry about passing other data types, in fact, all our constraints can take slots and events as args and create the relevant arrays themselves so that would clean up some other things too.

I'll pick this up today 🙂👍
