### ISSUE TITLE
Get a diff between two schedules

### ISSUE THREAD

**Issue by alexwlchan** [PyconUK/ConferenceScheduler#30]
If I’ve made a change to an existing schedule using #4, it would be useful to be able to see a diff of the changes – e.g., so I can notify any speakers who’ve moved, and attendees can tweak their plans without having to re-read the entire schedule.

I don’t think this has to be provided when you recompute the schedule, but a way to compare two schedules would probably be useful.

Maybe the diff function generates tuples of the form `(event, old_slot, new_slot)`?

If you assume events stay the same, something like this:

```python
class ChangedScheduledItem(NamedTuple):
    event: Event
    old_slot: Slot
    new_slot: Slot


def diff_schedules(old_schedule, new_schedule):
    old_schedule = sorted(old_schedule, key=lambda item: item.event)
    new_schedule = sorted(new_schedule, key=lambda item: item.event)
    for (event, old_slot), (_, new_slot) in zip(old_schedule, new_schedule):
        if old_slot != new_slot:
            yield ChangedScheduledItem(event, old_slot, new_slot)
```

Although in practice, I think you'd want some extra logic to cope with events being added or removed, in which case maybe you put `None` as the old/new slot?

**Comment by drvinceknight** [comment]
> Although in practice, I think you'd want some extra logic to cope with events being added or removed, in which case maybe you put None as the old/new slot?

Using `None` sounds good although in practice events being added or removed is actually a simpler problem from a scheduling point of view: you just don't do anything and "rename" that event to be empty. But for the purpose of the diff using `None` is the way to go! :+1:

**Comment by meatballs** [comment]
I think there are two variations of this: an event based view and a slot based view.

i.e. As described above, "For the given events, which of them have been moved to a different slot?"
and also "Which slots now have different events scheduled from previously?"

**Comment by drvinceknight** [comment]
Good idea, perhaps `event_diff_schedule` and `slot_diff_schedule` as two functions?

**Comment by meatballs** [comment]
I'll pick this up next
