### ISSUE TITLE
Code optimisation - use pulp summation?

### ISSUE THREAD

**Issue by drvinceknight** [PyconUK/ConferenceScheduler#36]
The constraints and objective functions use python summation to gather the variables.

Apparently this is not efficient and it's better to use `pulp.LpAffineExpression.addInPlace` as explained here: https://gist.github.com/DRMacIver/4b6561c8e4776597bf7568ccac52742f#file-fullrigger-py-L7

**Comment by meatballs** [comment]
I'll pick this one up
