### ISSUE TITLE
Bug with pip installed version

### ISSUE THREAD

**Issue by drvinceknight** [PyconUK/ConferenceScheduler#51]
```
>>> from conference_scheduler import scheduler
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-120-74aea00c250d> in <module>()
----> 1 import conference_scheduler.lp_problem
      2 from conference_scheduler import scheduler
      3 schedule = scheduler.schedule(events, slots)

ModuleNotFoundError: No module named 'conference_scheduler.lp_problem'
```

I think this might be because something is not included in the `setup.py` but I'm not sure.  (Works fine using an install from source.)

(Side note: this could also indicate that we should perhaps move to a `root/src/conference_scheduler` and `root/tests` directory setup so that we also test an installed version of the library? (Using `python setup.py test`) I did this for Nashpy after reading about the advantages.)

**Comment by alexwlchan** [comment]
I’ll have a quick look at this, I have a vague idea of what might be going wrong.
