### ISSUE TITLE
Return the final solution as a list (currently a generator)

### ISSUE THREAD

**Issue by drvinceknight** [PyconUK/ConferenceScheduler#58]
Perhaps as a sorted list by the `starts_at` values?

```
sorted(schedule, key=lambda item: item.slot.starts_at)
```

EDIT: My reasoning for this is that it might well take ours for a solution to come back for some set of constraints etc... It feels like things should be a bit more permanent in those cases. (Perhaps I worry too much...)

**Comment by drvinceknight** [comment]
If we want to stick with generators, how about a how to: "How to obtain all representations of a schedule" or something like that, in there we'd show how to get the mathematical solution and the array from a schedule (basically just showing how to use the `solution_to...` functions). That could be useful anyway (even if we do move away from the generators).

**Comment by meatballs** [comment]
As @drvinceknight pointed out, given that pulp returns a list in the first place, we aren't really saving anything by using a generator ourselves. Although it seems a shame, it's probably best to move to a list.

**Comment by drvinceknight** [comment]
I'll pick this up.
