### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by drvinceknight** [PyconUK/ConferenceScheduler#6]
Within the documentation we can include a section on the mathematical model behind it :)

**Comment by drvinceknight** [comment]
I'm giving this a start: I'm going to assume we're going with sphinx etc. 

My plan is to use @evildmp's documentation quadrant which suggest that all documentation is one of 4 things:

1. Tutorial
2. How tos
3. Discussion
4. Reference

So in this case the **tutorial** would be a walk through of building and scheduling an example conference (I don't suggest we're ready to write that yet). **How to**'s would be quick (similar to the Axelrod tutorials) to the point: "This is how you would add another constraint" (I don't suggest we're ready to write that just yet). **Background** would be the background which in this case would include the mathematical formulation of the problem: this is what I'm going to start writing up. I think it's good to have it down (perhaps just for my benefit) to ensure we have a formal write up of the mathematical problem.

**Comment by meatballs** [comment]
Yep. And the reference should include an auto generation from (as yet non-existent) docstrings
