### ISSUE TITLE
Event Methods

### ISSUE THREAD

**Issue by meatballs** [PyconUK/ConferenceScheduler#76]
We have created an Event class - largely because we realised that an Event's state needs to change after it has been initialised (its unavailability). However, we are still manipulating its `unavailability` attribute directly within our code.

I suggest that, instead, we should create getter/setter methods to provide some isolation. My initial thoughts are something like the following:

```
def set_unavailable_for_slot(self, slot):
    """Sets the event to be unavailable for the given slot"""

def set_unavailable_at(self, unavailable_from, unavailable_until):
    """Sets the event to be unavailable for a period of time"""

def set_to_avoid(self, event):
    """Sets the event's unavailability so as to avoid a clash with the given event"""

def is_unavailable_for(self, slot):
    """A boolean returning true if the event is unavailable for the given slot, false otherwise"""
```

**Comment by drvinceknight** [comment]
Any reason why we don't want to manipulate it directly?

**Comment by meatballs** [comment]
Encapsulation - good practice!

**Comment by drvinceknight** [comment]
I feel that having them as simple lists that are easily manipulated is a strength. As long as we don't lose that functionality I don't see a problem with adding these extra helpful functions. 👍

**Comment by meatballs** [comment]
We should at least wrap it in a property rather than accessing it directly. That way, we can add validation later if we need without breaking existing code (i.e. the main benefit of encapsulation - not breaking the calling code when changing the internal implementation of a class).

**Comment by drvinceknight** [comment]
> Encapsulation

Looks a lot like abstraction/complication in this case to me. As a user I'd rather just manipulate them how I wish to without having to learn more things about the library. As long as that functionality​ is still there I'm fine. We could add a "how to" use these event class methods for setting unavailability but it should not be in the opening tutorial.

**Comment by meatballs** [comment]
> As a user I'd rather just manipulate them how I wish to without having to learn more things about the library

That's the whole point of encapsulation. If the internal implementation of the class changes, for whatever reason, the calling mechanism does not. The user of that class doesn't need to change anything and doesn't need to know what's been done or why.

**Comment by meatballs** [comment]
Final statement at https://pythonspot.com/en/encapsulation/

> Encapsulation gives you more control over the degree of coupling in your code, it allows a class to change its implementation without affecting other parts of the code.

**Comment by drvinceknight** [comment]
I always err on the side of less abstractions and simplicity so perhaps I'm not seeing some potential future needed complexity which warrant this.

I would vote for just one method that adds both a slot or event to the unavailability (basically something to mimic the `append`/`extend` method on the list).

```python
event.set_unavailable(thing):
```

Leaving things like duration etc to the users. Otherwise we could end up adding a large number of methods for further cases always trying to double guess use cases.

**Comment by meatballs** [comment]
OK, I can live with that! Thinking about it, we are adding unavailability rather than setting it, so how about `add_unavailability(thing):`?

**Comment by drvinceknight** [comment]
Yup I prefer that. Also perhaps `remove_unavailability`?

If we're just adding this one method (and the remove one) then I'd change my mind on the tutorial and include that in there. (And this just becomes THE way to do it).

**Comment by drvinceknight** [comment]
Dammit look at me adding more method suggestions, perhaps:

- `wipe_unavailability` to set the unavailability to `[]`

Basically thinking of things that we can currently do on lists.
