### ISSUE TITLE
Reference Section

### ISSUE THREAD

**Issue by meatballs** [PyconUK/ConferenceScheduler#79]
Write the reference documentation - as much as possible based on autodoc from the library docstrings.

**Comment by drvinceknight** [comment]
I've pushed this commit https://github.com/PyconUK/ConferenceScheduler/commit/b2bc34163da3dcccab0893eaea36acecf74e7655 

but it comes with a couple of problems:

- Doesn't build unless using py3.6 (so on rtd we'll need to ensure that we're using 3.6, which can be done using a conda env file - we do this on Axelrod - another option is to mock the files that are causing problems)
- The section headers in the docstrings are causing problems.

There might be a better way of doing this all together but leaving that there in case it's helpful as a starting point.
